# This is an example YAML configuration.

# This simulation creates two features: rainfall and mean_temperature,
# and calculate disease bases based on these features (climate_dependency).
# We apply a lagged effect of 2 (weeks or months based on time granularity) which
# cause a dealy in the effect of climate features.
# It does not take earlier disease_values into account (auto_regressive: False).
# It simulates one regions with a population of 100, and two rain-season between
# week 10 and 23, and week 35 and 40.

model:
  simulation_name: "climate_dependent_non_autoregressive"
  time_granularity: "D"
  simulation_length: 100
  features:
    - name: "rainfall"
      modification:
        - function: "poisson_distribution"
          params:
            lam: 2
            scale: 1
        - function: "stochastic_noise"
          params:
            mean: 1
            std_dev: 2
    - name: "temperature"
      modification:
        - function: "seasonal"
          params:
            average: 25
            amplitude: 5
            pahse: 0
    - name: "sickness"
      modifications:
        function: "climate_dependent_disease_cases"
        params:
          lags: [2, 2]
          auto_regressive: False
          phi: [0.5, 0.5]

  regions:
    - name: "Region"
      region_id: 1
      rain_season: [[10, 23], [35, 40]]
      neighbour: [2]
      population: 100
